import { z } from "zod";
import { StorageProvider, StoreFileInput, StorageResult } from "./types.js";

/**
 * Zod schema for Notion storage configuration.
 */
export const NotionStorageConfigSchema = z.object({
  /** Notion API integration token (starts with 'secret_'). */
  token: z.string().min(1),

  /** Target page ID where files will be uploaded. */
  pageId: z.string().min(1),

  /** Optional database ID to create entries in. */
  databaseId: z.string().optional(),
});

export type NotionStorageConfig = z.infer<typeof NotionStorageConfigSchema>;

/**
 * Storage provider that uploads files to Notion.
 *
 * Files are uploaded as external file blocks to a Notion page.
 * Note: Notion doesn't natively host files, so this provider
 * creates file blocks linking to temporary URLs from Napkin AI.
 * For persistent storage, consider using S3 or Google Drive.
 *
 * @example
 * ```typescript
 * const storage = new NotionStorageProvider({
 *   token: "secret_abc123",
 *   pageId: "12345678-abcd-1234-abcd-123456789abc",
 * });
 *
 * const result = await storage.store({
 *   content: svgBuffer,
 *   filename: "diagram.svg",
 *   mimeType: "image/svg+xml",
 * });
 * ```
 */
export class NotionStorageProvider implements StorageProvider {
  readonly type = "notion";
  private readonly config: NotionStorageConfig;
  private readonly baseUrl = "https://api.notion.com/v1";
  private readonly notionVersion = "2022-06-28";

  constructor(config: NotionStorageConfig) {
    this.config = NotionStorageConfigSchema.parse(config);
  }

  async store(input: StoreFileInput): Promise<StorageResult> {
    const content = Buffer.isBuffer(input.content)
      ? input.content
      : Buffer.from(input.content, "base64");

    // Convert to base64 data URL for embedding
    const base64 = content.toString("base64");
    const dataUrl = `data:${input.mimeType};base64,${base64}`;

    // Create a block in the page with the image
    const response = await globalThis.fetch(
      `${this.baseUrl}/blocks/${this.config.pageId}/children`,
      {
        method: "PATCH",
        headers: {
          Authorization: `Bearer ${this.config.token}`,
          "Content-Type": "application/json",
          "Notion-Version": this.notionVersion,
        },
        body: JSON.stringify({
          children: [
            {
              object: "block",
              type: "image",
              image: {
                type: "external",
                external: {
                  url: dataUrl,
                },
              },
            },
            {
              object: "block",
              type: "paragraph",
              paragraph: {
                rich_text: [
                  {
                    type: "text",
                    text: {
                      content: `${input.filename} - Generated by Napkin AI`,
                    },
                  },
                ],
              },
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Failed to upload to Notion: ${response.status} ${error}`);
    }

    const result = (await response.json()) as { results: Array<{ id: string }> };
    const blockId = result.results?.[0]?.id ?? "unknown";

    return {
      location: `notion://${this.config.pageId}/${blockId}`,
      publicUrl: `https://notion.so/${this.config.pageId.replace(/-/g, "")}`,
      metadata: {
        pageId: this.config.pageId,
        blockId,
        filename: input.filename,
      },
    };
  }

  isConfigured(): boolean {
    return Boolean(this.config.token && this.config.pageId);
  }
}
