import { WebClient } from "@slack/web-api";
import { z } from "zod";
import { StorageProvider, StoreFileInput, StorageResult } from "./types.js";

/**
 * Zod schema for Slack storage configuration.
 */
export const SlackStorageConfigSchema = z.object({
  /** Slack channel ID to upload files to. */
  channelId: z.string().min(1),

  /** Slack bot token (can also use SLACK_BOT_TOKEN environment variable). */
  token: z.string().optional(),

  /** Initial comment to post with the file. */
  initialComment: z.string().optional(),
});

export type SlackStorageConfig = z.infer<typeof SlackStorageConfigSchema>;

/**
 * Storage provider that uploads files to Slack.
 *
 * Requires a Slack bot token with files:write permission and access to the
 * target channel. The bot must be added to the channel before uploading.
 *
 * @example
 * ```typescript
 * const storage = new SlackStorageProvider({
 *   channelId: "C0123456789",
 *   token: "xoxb-...",
 *   initialComment: "Generated by Napkin AI",
 * });
 *
 * const result = await storage.store({
 *   content: pngBuffer,
 *   filename: "diagram.png",
 *   mimeType: "image/png",
 * });
 *
 * console.log(result.publicUrl); // Slack file permalink
 * ```
 */
export class SlackStorageProvider implements StorageProvider {
  readonly type = "slack";
  private readonly config: SlackStorageConfig;
  private client: WebClient | null = null;

  constructor(config: SlackStorageConfig) {
    this.config = SlackStorageConfigSchema.parse(config);
  }

  private getClient(): WebClient {
    if (this.client) {
      return this.client;
    }

    const token = this.config.token ?? process.env.SLACK_BOT_TOKEN;

    if (!token) {
      throw new Error(
        "Slack token not configured. " +
          "Provide token in config or set SLACK_BOT_TOKEN environment variable."
      );
    }

    this.client = new WebClient(token);
    return this.client;
  }

  async store(input: StoreFileInput): Promise<StorageResult> {
    const client = this.getClient();

    const content = Buffer.isBuffer(input.content)
      ? input.content
      : Buffer.from(input.content, "base64");

    const response = await client.files.uploadV2({
      channel_id: this.config.channelId,
      file: content,
      filename: input.filename,
      initial_comment: this.config.initialComment,
    });

    const files = (
      response as {
        files?: Array<{ id: string; name?: string; permalink?: string; url_private?: string }>;
      }
    ).files;
    const file = files?.[0];

    if (!file) {
      throw new Error("Failed to upload file to Slack: no file returned");
    }

    return {
      location: `slack://${this.config.channelId}/${file.id}`,
      publicUrl: file.permalink,
      metadata: {
        fileId: file.id,
        channelId: this.config.channelId,
        name: file.name,
        permalink: file.permalink,
        urlPrivate: file.url_private,
      },
    };
  }

  isConfigured(): boolean {
    return Boolean(this.config.channelId && (this.config.token || process.env.SLACK_BOT_TOKEN));
  }
}
